apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    cni.projectcalico.org/containerID: 3de69e645365b89d77cd0b233807d9e8fc6a055ba108899cbf536899362b0732
    cni.projectcalico.org/podIP: 172.21.7.98/32
    cni.projectcalico.org/podIPs: 172.21.7.98/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.21.7.98"
          ],
          "default": true,
          "dns": {}
      }]
    libertyOperator: WebSphere Liberty
    openshift.io/sa.scc.uid-range: 1001/1
    openshift.io/scc: restricted-v2
    productChargedContainers: app
    productID: e7daacc46bbe4e2dacd2af49145a4723
    productMetric: PROCESSOR_VALUE_UNIT
    productName: IBM WebSphere Application Server
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-06-20T12:13:30Z"
  generateName: account-iam-844cf69bc8-
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: account-iam
    app.kubernetes.io/managed-by: websphere-liberty-operator
    app.kubernetes.io/name: account-iam
    app.kubernetes.io/part-of: account-iam
    bcdr-candidate: t
    by-squad: mcsp-user-management
    component-name: iam-services
    for-product: all
    liberty.websphere.ibm.com/name: account-iam
    name: account-iam
    pod-template-hash: 844cf69bc8
  name: account-iam-844cf69bc8-lmbn8
  namespace: msp-user-manager
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: account-iam-844cf69bc8
    uid: a3a0045f-5d16-4ac0-8528-83d6f424b863
  resourceVersion: "201347903"
  uid: 8f21a48f-f20b-4cf9-8122-d2825d7be688
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: account-iam
          topologyKey: topology.kubernetes.io/zone
        weight: 50
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: account-iam
          topologyKey: kubernetes.io/hostname
        weight: 50
  automountServiceAccountToken: true
  containers:
  - env:
    - name: TLS_DIR
      value: /etc/x509/certs
    - name: SA_RESOURCE_VERSION
      value: "157072899"
    - name: WLP_LOGGING_CONSOLE_LOGLEVEL
      value: info
    - name: WLP_LOGGING_CONSOLE_SOURCE
      value: message,accessLog,ffdc,audit
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: json
    - name: SEC_IMPORT_K8S_CERTS
      value: "true"
    - name: SERVICE_CERT_SECRET_RESOURCE_VERSION
      value: "114243033"
    envFrom:
    - configMapRef:
        name: account-iam-env-configmap-staging
    image: icr.io/automation-saas-platform/access-management/account-iam:20240620103839-main-26018133515e4db5501f3a0e58b6c56a3ee53e3e
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /api/2.0/health/liveness
        port: 9445
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: app
    ports:
    - containerPort: 9445
      name: 9445-tcp
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/2.0/health/readiness
        port: 9445
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 1500m
        memory: 800Mi
      requests:
        cpu: 300m
        memory: 400Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000940000
      seccompProfile:
        type: RuntimeDefault
    startupProbe:
      failureThreshold: 60
      httpGet:
        path: /api/2.0/health/started
        port: 9445
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: account-iam-token
    - mountPath: /config/variables/oidc
      name: account-iam-oidc
      readOnly: true
    - mountPath: /etc/x509/certs-autobackup
      name: account-iam-cert-bk
      readOnly: true
    - mountPath: /config/variables/okd
      name: account-iam-okd
      readOnly: true
    - mountPath: /config/variables
      name: account-iam-variables
      readOnly: true
    - mountPath: /var/database/ca
      name: account-iam-database-ca
      readOnly: true
    - mountPath: /etc/x509/certs
      name: svc-certificate
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-txptw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: account-iam-global-registry-secret
  - name: account-iam-dockercfg-bfsvq
  nodeName: 192.168.34.33
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000940000
    seLinuxOptions:
      level: s0:c31,c5
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: account-iam
  serviceAccountName: account-iam
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: account-iam
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: account-iam
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
  volumes:
  - name: account-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: openshift
          expirationSeconds: 7200
          path: account-iam-token
  - name: account-iam-oidc
    secret:
      defaultMode: 420
      secretName: account-iam-oidc-client-auth
  - name: account-iam-cert-bk
    secret:
      defaultMode: 420
      secretName: account-iam-svc-tls-cm-autobackup
  - name: account-iam-okd
    secret:
      defaultMode: 420
      secretName: account-iam-okd-auth
  - name: account-iam-variables
    projected:
      defaultMode: 420
      sources:
      - secret:
          name: account-iam-database-secret
      - secret:
          name: account-iam-mpconfig-secrets
  - configMap:
      defaultMode: 420
      name: account-iam-database-ca-configmap
    name: account-iam-database-ca
  - name: svc-certificate
    secret:
      defaultMode: 420
      secretName: account-iam-svc-tls-cm
  - name: kube-api-access-txptw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-20T12:13:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-20T12:14:34Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-20T12:14:34Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-20T12:13:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://1ecd4165893230314925e7304ea49c9600e865c84417cc1ae49ed25dd5453b86
    image: icr.io/automation-saas-platform/access-management/account-iam:20240620103839-main-26018133515e4db5501f3a0e58b6c56a3ee53e3e
    imageID: icr.io/automation-saas-platform/access-management/account-iam@sha256:0c3034e28925367e1b6b2a571580dc1fb89697594dc3bd848889d2ba1e273ce2
    lastState: {}
    name: app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-20T12:13:31Z"
  hostIP: 192.168.34.33
  phase: Running
  podIP: 172.21.7.98
  podIPs:
  - ip: 172.21.7.98
  qosClass: Burstable
  startTime: "2024-06-20T12:13:30Z"
