apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 58a597c6fa6deef24b09938123da75dcb4b67901cd3be293a36d46e56818442c
    cni.projectcalico.org/podIP: 172.21.153.36/32
    cni.projectcalico.org/podIPs: 172.21.153.36/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.21.153.36"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-06-11T17:33:44Z"
  generateName: cloudrock-nw-controller-77b976976c-
  labels:
    app: cloudrock-nw-controller
    by-squad: mcsp-controlplane
    for-product: all
    pod-template-hash: 77b976976c
  name: cloudrock-nw-controller-77b976976c-nzhzb
  namespace: cloudrock-controller
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cloudrock-nw-controller-77b976976c
    uid: bab89c95-f5c3-4186-b346-05edc04b8475
  resourceVersion: "175980641"
  uid: e37bfdb7-5875-4546-9557-c38b01c8d63a
spec:
  automountServiceAccountToken: true
  containers:
  - env:
    - name: CONTROLLER_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: CONTROLLER_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: CONTROLLER_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: AWS_REGION
      value: us-east-1
    - name: OPERATOR_NAME
      value: cloudrock-nw-controller
    - name: ROSA_TOKEN_PATH
      value: /secrets/rosatoken
    - name: CR_CFG_FILEPATH
      value: /config/embed/config.yaml
    - name: ENABLE_WEBHOOKS
      value: "true"
    - name: SLACK_BOT_TOKEN_PATH
      value: /secrets/slackbottoken
    - name: SLACK_CHANNEL_ID_PATH
      value: /secrets/slackchannelid
    - name: PULL_SECRET_PATH
      value: /secrets/pullsecret
    image: icr.io/cr-controlplane-release/cloudrock-nw-controller:1.2.3-amd64
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 8081
      timeoutSeconds: 5
    name: cloudrock-controller
    ports:
    - containerPort: 9443
      name: webhook-server
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      initialDelaySeconds: 12
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 8081
      timeoutSeconds: 6
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000680000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /secrets
      mountPropagation: None
      name: cloudrock-controller-secrets
      readOnly: true
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      mountPropagation: None
      name: cert
      readOnly: true
    - mountPath: /.aws
      mountPropagation: None
      name: aws-credential
    - mountPath: /.config
      mountPropagation: None
      name: ocm
    - mountPath: /tokens
      mountPropagation: None
      name: admin-tokens
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kjn6v
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: controlplane-imagepullsecret
  - name: cloudrock-controller-dockercfg-8vl92
  nodeName: 192.168.33.25
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000680000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c26,c15
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: cloudrock-controller
  serviceAccountName: cloudrock-controller
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: cert
    secret:
      defaultMode: 420
      optional: false
      secretName: webhook-server-cert
  - name: cloudrock-controller-secrets
    secret:
      defaultMode: 420
      optional: false
      secretName: cloudrock-controller-secrets
  - emptyDir:
      sizeLimit: 1Mi
    name: aws-credential
  - emptyDir:
      sizeLimit: 1Mi
    name: ocm
  - emptyDir:
      sizeLimit: 1Mi
    name: admin-tokens
  - name: kube-api-access-kjn6v
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T17:33:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T17:34:04Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T17:34:04Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-11T17:33:44Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://787920ceb34a29262c9998b03c96977ce11618ed7a9cfbaefbb6512b11446a97
    image: icr.io/cr-controlplane-release/cloudrock-nw-controller:1.2.3-amd64
    imageID: icr.io/cr-controlplane-release/cloudrock-nw-controller@sha256:87c92f70ec963065bda18761c3b54edce3adda2a36dc8e99fa8c7563b6483528
    lastState: {}
    name: cloudrock-controller
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-11T17:33:51Z"
  hostIP: 192.168.33.25
  phase: Running
  podIP: 172.21.153.36
  podIPs:
  - ip: 172.21.153.36
  qosClass: Burstable
  startTime: "2024-06-11T17:33:44Z"
