apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 3969f751c29db119d460596c667ebdd304f3c7cdcd7cbcab5d383b0896ebdd75
    cni.projectcalico.org/podIP: 172.21.71.241/32
    cni.projectcalico.org/podIPs: 172.21.71.241/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.21.71.241"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-06-21T12:02:30Z"
  generateName: ibm-saas-console-onboarding-deployment-stage-94bcc77f9-
  labels:
    app: ibm-saas-console-onboarding
    pod-template-hash: 94bcc77f9
    version: 1.2.0
  name: ibm-saas-console-onboarding-deployment-stage-94bcc77f9-m8bjc
  namespace: ibm-saas-console
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ibm-saas-console-onboarding-deployment-stage-94bcc77f9
    uid: 3b8517ff-efbd-4eb2-8bb6-b095811c4c8d
  resourceVersion: "204088783"
  uid: 612134fc-392e-4c40-b5f4-b56d1e57d56d
spec:
  automountServiceAccountToken: true
  containers:
  - env:
    - name: DEPLOYMENT_ENV
      valueFrom:
        configMapKeyRef:
          key: DEPLOYMENT_ENV
          name: ibm-saas-console-config-stage
    - name: CALLBACK_URL
      valueFrom:
        configMapKeyRef:
          key: CALLBACK_URL
          name: ibm-saas-console-config-stage
    - name: API_OAUTH_TOKEN_URL
      valueFrom:
        configMapKeyRef:
          key: API_OAUTH_TOKEN_URL
          name: ibm-saas-console-config-stage
    - name: CERT_DIR
      valueFrom:
        configMapKeyRef:
          key: CERT_DIR
          name: ibm-saas-console-config-stage
    - name: ISSUER_BASE_URL
      valueFrom:
        configMapKeyRef:
          key: ISSUER_BASE_URL
          name: ibm-saas-console-config-stage
    - name: APOLLO_CLIENT_API_URL
      valueFrom:
        configMapKeyRef:
          key: APOLLO_CLIENT_API_URL
          name: ibm-saas-console-config-stage
    - name: REDIS_HOST
      valueFrom:
        configMapKeyRef:
          key: REDIS_HOST
          name: ibm-saas-console-config-stage
    image: icr.io/mcsp/ui/onboarding_service:fix-redis-ab8ada1141896e8d2bedaa7e520d9445d04a99d0
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz/liveness
        port: 3002
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: ibm-saas-console-onboarding
    ports:
    - containerPort: 3002
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz/readiness
        port: 3002
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000920000
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/app-root/src/apps/onboarding/.env
      name: ibm-saas-console-secrets-stage
      readOnly: true
      subPath: .env
    - mountPath: /opt/app-root/src/security
      name: ibm-saas-console-onboarding-server-stage-tls
      readOnly: true
    - mountPath: /mnt/tls
      name: tls
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-thmll
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: ibm-saas-console-pull-secret
  nodeName: 192.168.34.34
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000920000
    seLinuxOptions:
      level: s0:c30,c25
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: ibm-saas-console-sa
  serviceAccountName: ibm-saas-console-sa
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: ibm-saas-console-secrets-stage
    secret:
      defaultMode: 420
      secretName: ibm-saas-console-secrets-stage
  - name: ibm-saas-console-onboarding-server-stage-tls
    secret:
      defaultMode: 420
      secretName: ibm-saas-console-onboarding-server-stage-tls
  - configMap:
      defaultMode: 420
      items:
      - key: service-ca.crt
        path: ca.crt
      name: openshift-service-ca.crt
    name: tls
  - name: kube-api-access-thmll
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T12:02:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T12:05:51Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T12:05:51Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T12:02:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://3fa116009b5f1e8a76c35a6e8fe425140b82e91a6ec56e9151f14ed6cf6e3f55
    image: icr.io/mcsp/ui/onboarding_service:fix-redis-ab8ada1141896e8d2bedaa7e520d9445d04a99d0
    imageID: icr.io/mcsp/ui/onboarding_service@sha256:4f703c5c6b0b88b9716b6f9ec3dc9acdb67a7b1c366a421762fea57e0bbb6cd1
    lastState: {}
    name: ibm-saas-console-onboarding
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-21T12:05:36Z"
  hostIP: 192.168.34.34
  phase: Running
  podIP: 172.21.71.241
  podIPs:
  - ip: 172.21.71.241
  qosClass: Burstable
  startTime: "2024-06-21T12:02:30Z"
