apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 372ca87404c44f92c92cab6ce2547dc9c2a51b07d152212c6d304eb387bfac04
    cni.projectcalico.org/podIP: 172.21.38.49/32
    cni.projectcalico.org/podIPs: 172.21.38.49/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.21.38.49"
          ],
          "default": true,
          "dns": {}
      }]
    libertyOperator: WebSphere Liberty
    openshift.io/scc: restricted-v2
    productChargedContainers: app
    productID: e7daacc46bbe4e2dacd2af49145a4723
    productMetric: PROCESSOR_VALUE_UNIT
    productName: IBM WebSphere Application Server
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-06-21T22:51:58Z"
  generateName: tenantmgtms-5dd7f88c78-
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: tenantmgtms
    app.kubernetes.io/managed-by: websphere-liberty-operator
    app.kubernetes.io/name: tenantmgtms
    app.kubernetes.io/part-of: tenantmgtms
    bcdr-candidate: t
    by-squad: mcsp-instance-management
    component-name: tenant-management
    for-product: all
    liberty.websphere.ibm.com/name: tenantmgtms
    name: tenantmgtms
    pod-template-hash: 5dd7f88c78
  name: tenantmgtms-5dd7f88c78-h7pmp
  namespace: tenant-management
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: tenantmgtms-5dd7f88c78
    uid: ce196f14-1c9b-4cbc-bc74-ce287a164b53
  resourceVersion: "205291053"
  uid: be882a93-adbd-4d75-8e71-2ec1523643b8
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: tenantmgtms
          topologyKey: topology.kubernetes.io/zone
        weight: 50
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: tenantmgtms
          topologyKey: kubernetes.io/hostname
        weight: 50
  automountServiceAccountToken: true
  containers:
  - env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_IMAGE_NAME
      value: icr.io/automation-saas-platform/tenant-management/tenantmgt:20240621002639-main-9ee724819c6a28f6da8cbf10d32cd33f15c1da0d
    - name: TLS_DIR
      value: /etc/x509/certs
    - name: SA_RESOURCE_VERSION
      value: "112163616"
    - name: WLP_LOGGING_CONSOLE_LOGLEVEL
      value: info
    - name: WLP_LOGGING_CONSOLE_SOURCE
      value: message,accessLog,ffdc,audit
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: json
    - name: SEC_IMPORT_K8S_CERTS
      value: "true"
    - name: SERVICE_CERT_SECRET_RESOURCE_VERSION
      value: "112163671"
    envFrom:
    - configMapRef:
        name: tenantmgtms-env-configmap-staging
    image: icr.io/automation-saas-platform/tenant-management/tenantmgt:20240621002639-main-9ee724819c6a28f6da8cbf10d32cd33f15c1da0d
    imagePullPolicy: Always
    name: app
    ports:
    - containerPort: 9443
      name: 9443-tcp
      protocol: TCP
    resources:
      limits:
        cpu: 1500m
        memory: 1500Mi
      requests:
        cpu: 500m
        memory: 1000Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000960000
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: tenantmgtms-token
    - mountPath: /config/variables/oidc
      name: tenantmgtms-oidc
      readOnly: true
    - mountPath: /config/variables/okd
      name: tenantmgtms-okd
      readOnly: true
    - mountPath: /config/variables
      name: tenantmgtms-mpconfig
      readOnly: true
    - mountPath: /etc/x509/certs
      name: svc-certificate
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xfc7n
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: tenantmgtms-global-registry-secret
  - name: tenantmgtms-dockercfg-fqgkr
  nodeName: 192.168.32.25
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000960000
    seLinuxOptions:
      level: s0:c31,c15
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: tenantmgtms
  serviceAccountName: tenantmgtms
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: tenantmgtms
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: tenantmgtms
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
  volumes:
  - name: tenantmgtms-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: openshift
          expirationSeconds: 7200
          path: tenantmgtms-token
  - name: tenantmgtms-oidc
    secret:
      defaultMode: 420
      secretName: tenantmgtms-oidc-client-auth
  - name: tenantmgtms-okd
    secret:
      defaultMode: 420
      secretName: tenantmgtms-okd-auth
  - name: tenantmgtms-mpconfig
    secret:
      defaultMode: 420
      secretName: tenantmgtms-mpconfig-secrets
  - name: svc-certificate
    secret:
      defaultMode: 420
      secretName: tenantmgtms-svc-tls-cm
  - name: kube-api-access-xfc7n
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T22:51:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T22:52:12Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T22:52:12Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-21T22:51:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://767458c642866a14c71843cc5558fbd6d3a6d07d9ed64d7ec4fea0edfaf4fe84
    image: icr.io/automation-saas-platform/tenant-management/tenantmgt:20240621002639-main-9ee724819c6a28f6da8cbf10d32cd33f15c1da0d
    imageID: icr.io/automation-saas-platform/tenant-management/tenantmgt@sha256:da774b440d38b0ff304a36c3290b7e4b0a87a119bc8b0dc109a1489dc53926f8
    lastState: {}
    name: app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-21T22:52:12Z"
  hostIP: 192.168.32.25
  phase: Running
  podIP: 172.21.38.49
  podIPs:
  - ip: 172.21.38.49
  qosClass: Burstable
  startTime: "2024-06-21T22:51:58Z"
